jobs:
- job: Build
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:latest
  steps:
  - script: |
      cd /root/wheels
      git fetch
      git reset --hard $(Build.Repository.BranchName) || true

  - script: |
      mkdir build
      /root/scripts/resolve_refs.py /root/conf /root/wheels ./build $(Build.Repository.Uri) $(Build.SourceBranch)

  - script: |
      cd build
      ./install.sh
      source virtualenv/bin/activate
      grep '^def test_' ./src/*/tests/test_*.py | sed 's/def //' | cut -d '(' -f 1 | /root/scripts/filter-tests.py --eval-attribute 'speed != "slow"' > tests.txt
      cd ..
      tar -czf build.tar.gz build/src build/virtualenv build/tests.txt

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "Build archive"
      targetPath: ./build.tar.gz

- job: Test
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:latest
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: "Build archive"
      targetPath: .

  - script: |
      tar -xf build.tar.gz
      cd build
      /root/scripts/test.sh tests.txt

