jobs:
- job: Build
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:latest
  steps:
  - script: ./ci-settings/scripts/latest_deps.sh

  - script: |
      mkdir build
      ./ci-settings/scripts/resolve_refs.py ./ci-settings/conf ./build $(Build.Repository.Uri) $(Build.SourceBranch)

  - script: |
      cd build
      ./install.sh
      source virtualenv/bin/activate
      grep '^def test_' ./src/*/tests/test_*.py | sed 's/def //' | cut -d '(' -f 1 | ../ci-settings-master/scripts/filter-tests.py --eval-attribute 'speed != "slow"' > tests.txt
      #cd ..
      #tar -czf build.tar.gz build/src build/virtualenv build/tests.txt

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: "Build archive"
      targetPath: ./build

- job: test
  pool:
    vmImage: ubuntu-16.04
  container:
    image: angr/ci:latest
  dependsOn: Build
  condition: succeeded()
  steps:
  - script: ./ci-settings/scripts/latest_deps.sh

  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: "Build archive"
      targetPath: .

  - script: |
      cd build
      ../ci-settings/scripts/test.sh tests.txt

